#pragma once

enum class ActionType : unsigned int {
	ActionAddTrack = 0x0001,
	ActionAddTrackAudioInput,
	ActionAddTrackMIDIInput,
	ActionAddTrackAudioSend,
	ActionAddTrackMIDISend,
	ActionAddEffect,
	ActionAddInstr,
	ActionAddTrackSideChainBus,
	ActionAddSequencerBlock,
	ActionAddTempoTempo,
	ActionAddTempoBeat,

	ActionSave = 0x0101,
	ActionSplitSequencerBlock,
	ActionLoadPluginState,

	ActionRemoveTrack = 0x0201,
	ActionRemoveTrackAudioInput,
	ActionRemoveTrackMIDIInput,
	ActionRemoveTrackAudioSend,
	ActionRemoveTrackMIDISend,
	ActionRemoveTrackAudioSendAllChannel,
	ActionRemoveTrackAudioSendOnSlot,
	ActionRemoveTrackMIDISendOnSlot,
	ActionRemoveEffect,
	ActionRemoveInstr,
	ActionRemoveInstrParamCCConnection,
	ActionRemoveEffectParamCCConnection,
	ActionRemoveTrackSideChainBus,
	ActionRemoveSequencerBlock,
	ActionRemoveTempo,

	ActionSetTrackGain = 0x0301,
	ActionSetTrackPan,
	ActionSetTrackFader,
	ActionSetEffectBypass,
	ActionSetInstrBypass,
	ActionSetInstrMidiChannel,
	ActionSetEffectMidiChannel,
	ActionSetInstrParamValue,
	ActionSetEffectParamValue,
	ActionSetInstrParamConnectToCC,
	ActionSetEffectParamConnectToCC,
	ActionSetInstrMidiCCIntercept,
	ActionSetEffectMidiCCIntercept,
	ActionSetEffectBypassByPtr,
	ActionSetInstrBypassByPtr,
	ActionSetInstrMidiChannelByPtr,
	ActionSetEffectMidiChannelByPtr,
	ActionSetInstrMidiCCInterceptByPtr,
	ActionSetEffectMidiCCInterceptByPtr,
	ActionSetInstrMidiOutputByPtr,
	ActionSetEffectMidiOutputByPtr,
	ActionSetInstrParamConnectToCCByPtr,
	ActionSetEffectParamConnectToCCByPtr,
	ActionSetTrackName,
	ActionSetTrackColor,
	ActionSetEffectIndex,
	ActionSetInstrOffline,
	ActionSetTempoTime,
	ActionSetTempoTempo,
	ActionSetTempoBeat,
	ActionSetTrackMute,
	ActionSetTrackSolo,
	ActionSetTrackRecording,
	ActionSetTrackInputMonitoring,
	ActionSetEffect,
	ActionSetCurrentMIDITrack,
	ActionSetSequencerBlockTime
};
