#pragma once

#define VS_AUDIO_PLATFORM_NAME			"VocalShaper"
#define VS_RELEASE_BRANCH				"Community"
#define VS_RELEASE_NAME					"Pinellia"

#define VS_MAJOR_VERSION				PROJECT_VERSION_MAJOR
#define VS_MINOR_VERSION				PROJECT_VERSION_MINOR
#define VS_PATCH_VERSION				PROJECT_VERSION_PATCH

#define VS_MINIMUM_SUPPORTED_MAJOR_VERSION		0
#define VS_MINIMUM_SUPPORTED_MINOR_VERSION		0
#define VS_MINIMUM_SUPPORTED_PATCH_VERSION		2
